services:
  - type: web
    name: whatsapp-ghl-backend
    env: node
    region: oregon
    plan: free
    buildCommand: |
      # Install Chromium dependencies
      apt-get update && apt-get install -y \
        chromium \
        chromium-sandbox \
        fonts-liberation \
        libasound2 \
        libatk-bridge2.0-0 \
        libatk1.0-0 \
        libatspi2.0-0 \
        libcups2 \
        libdbus-1-3 \
        libdrm2 \
        libgbm1 \
        libgtk-3-0 \
        libnspr4 \
        libnss3 \
        libwayland-client0 \
        libxcomposite1 \
        libxdamage1 \
        libxfixes3 \
        libxkbcommon0 \
        libxrandr2 \
        xdg-utils \
        || true
      # Install Node dependencies
      cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      # Venom-bot configuration for Render
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium
      - key: CHROME_BIN
        value: /usr/bin/chromium

