# render.yaml - Force npm instead of yarn
services:
  - type: web
    name: whatsapp-ghl-backend
    env: node
    region: oregon
    plan: free
    buildCommand: |
      # Install Node dependencies only (no Chromium needed for Baileys)
      cd backend && npm install --production --no-optional
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      # Force npm
      - key: NPM_CONFIG_PACKAGE_MANAGER
        value: npm
